### ISSUE TITLE
 training environment issue

### ISSUE THREAD

**Issue by ermu-tech** [yuhogun0908/MISOnet#3]
Hi! Your code is very clear, but I think I have encountered some issues about the version of packages while running your code. Could you please share your training environment of your code and the versions of each package? Thank you!

**Comment by ermu-tech** [comment]
By the way, could you please share the dataset you use to run the code? Thank you !

**Comment by jzi040941** [comment]
Hi, I've added requirements.txt file and updated README for environment setting
Thanks!

**Comment by yuhogun0908** [comment]
Hi
You can refer to the dataset github of the paper.

**Comment by ermu-tech** [comment]
Thank you for your reply! It's very useful. But there  was another problem: in run.py line 18, 'from tester import Tester' doesn't work, maybe you missed a 'test' file in your code?

**Comment by ermu-tech** [comment]
Hi! I took a look at your code, and now I have few other questions to consult：
1. From the way it's named, I think the file 'MISOnet/dataloader/REVERB_2MIX.py' is used to add reverb to mix signal, and  file 'MISOnet/dataloader/RIR_mixing.py' is used to add RIR to mix signal. But after looking though the code, I'am not sure what these two files are used for, could you please give some explanation in English? (It's a pity that I can't understand korean notes very well)
2. It seems that your code just MISO1(separation network), do you have the whole MISO1-BF-MISO3 system code and would like to share it?
Please excuse me if I misunderstood your code. 
Looking forward to your reply! Thank you!

**Comment by jzi040941** [comment]
Tester moudule is exactly same meaning as it's name, it's needed for testing
You can just comment out that line

Answer for 1:
At the time that we begin developing this repo we didn't have training dataset such as sms-wsj, libri-css
So we suppose to generate temporary dataset before we generate sms wsj dataset, that's why we implemented rir mixing
If you have sms-wsj dataset we dont need those thing

Answer for 2:
We are still developing system but not fully implemented whole system, 
We will make commit When the code is stabilized
Stay tune thanks

By the way, if you able to implement some part of systen feel free to make fork repo and make full request thanks

**Comment by ermu-tech** [comment]
Thank you for your reply! Can I assume that the two file 'REVERB_2MIX.py' and ' RIR_mixing.py' are used to generate temporary dataset? Actually I don't have sms-wsj, libri-css dataset, either. So do you mind to share which dataset you used to generate temporary dataset? Maybe it's much easier to run your code with that. Thank you!

**Comment by ermu-tech** [comment]
Hi! I'm not sure if you have seen my message above. I still wonder if you could share your dataset. Sorry to interrupt you !

**Comment by yuhogun0908** [comment]
Sorry to late answer.

Answer : Can I assume that the two file 'REVERB_2MIX.py' and ' RIR_mixing.py' are used to generate temporary dataset?

--> I used REVERB_2MIX.py, RIR_mixing.py dataset temporarily to implement and verify code. To be more specific, RIR mixing was performed through simulation through Matlab. RIR mixing method : Image method Paper : [J. B Allen and D. A. Berkley, "Image method for efficiently simulating small-room acoustics,"J.Acoust. Soc. Am. 65, 943-950(1979)]

Answer : Actually I don't have sms-wsj, libri-css dataset, either So do you mind to share which dataset you used to generate temporary dataset? Maybe it's much easier to run your code with that. 
--> You can proceed through https://github.com/fgnt/sms_wsj to make sms-wsj  and https://github.com/chenzhuo1011/libri_css to make libri-css.

sorry about that temporary dataset was removed after code implementation.
